export const assets = {
  gradient: "/assets/gradient.svg",
  square: "/assets/square.svg",
  cursor: "/assets/cursor.svg",
  movez: "/assets/movez-pin.svg",
  movezlarge: "/assets/movez-pin.svg",
  openai: "/assets/openai.svg",
  svelte: "/assets/icons/svelte.svg",
  foursquare: "/assets/icons/foursquare.svg",
  safari: "/assets/safari.webp",
  chrome: "/assets/chrome.svg",
  eventbrite: "/assets/icons/eventbrite.svg",
  meetup: "/assets/icons/meetup.svg",
  tripadvisor: "/assets/icons/tripadvisor.svg",
  notepad: "/assets/icons/notepad.svg",
  mobile: "/assets/mobile.svg",
  desktop: "/assets/desktop.svg",
  yelp: "/assets/icons/yelp.svg",
} as const;
